configuration:
  - Release
  - Debug

image:
  - Visual Studio 2013
  - Visual Studio 2015

platform:
  - x64

build_script:
  # build pthread
  - git clone https://github.com/GerHobbelt/pthread-win32.git C:/pthread-src
  - ps: "if ( $Env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2013' ) { $VS_VERSION='2013' } else { $VS_VERSION='2015' }"
  - ps: "msbuild C:/pthread-src/pthread.${VS_VERSION}.sln /p:Configuration=$Env:CONFIGURATION /p:Platform=x64"
  - ps: mkdir C:/pthread-win32
  - ps: mkdir C:/pthread-win32/include
  - ps: mkdir C:/pthread-win32/lib
  - ps: cp C:/pthread-src/pthread.h C:/pthread-win32/include
  - ps: cp C:/pthread-src/bin/x64_MSVC${VS_VERSION}.${Env:CONFIGURATION}/pthread_lib.lib C:/pthread-win32/lib
  # build SRT
  - ps: if ( $VS_VERSION -eq "2013" ) { $CMAKE_GENERATOR = "Visual Studio 12 2013 Win64" } else { $CMAKE_GENERATOR = "Visual Studio 14 2015 Win64" }
  - ps: cmake . -G"$CMAKE_GENERATOR" -DWITH_OPENSSL_INCLUDEDIR=C:/OpenSSL-Win64/include -DWITH_OPENSSL_LIBDIR=C:/OpenSSL-win64/lib/VC/static -DWITH_OPENSSL_LIBRARIES="libeay32MT.lib ssleay32MT.lib" -DWITH_PTHREAD_INCLUDEDIR=C:/pthread-win32/include -DWITH_PTHREAD_LDFLAGS=C:/pthread-win32/lib/pthread_lib.lib -DCMAKE_BUILD_TYPE=$Env:CONFIGURATION
  - msbuild Project.sln /p:Configuration=$Env:CONFIGURATION /p:Platform=x64
