configuration:
  - Release
  - Debug


image:
  - Visual Studio 2013
  - Visual Studio 2015

platform:
  - x64


build_script:
  # build pthread
  - git clone https://github.com/GerHobbelt/pthread-win32.git C:/pthread-src
  - ps: "if ( $Env{APPVEYOR_BUILD_WORKER_IMAGE} == 'Visual Studio 2013' ) { msbuild C:/pthread-src/pthread.2013.sln /p:Configuration=$Env{CONFIGURATION} /p:Platform:x64 }"
  - ps: "if ( $Env{APPVEYOR_BUILD_WORKER_IMAGE} == 'Visual Studio 2015' ) { msbuild C:/pthread-src/pthread.2015.sln /p:Configuration=$Env{CONFIGURATION} /p:Platform:x64 }"
  - ps: mkdir C:/pthread-win32
  - ps: mkdir C:/pthread-win32/include
  - ps: mkdir C:/pthread-win32/lib
  - ps: cp C:/pthread-src/pthread.h C:/pthread-win32/include
  - ps: "if ( $Env{APPVEYOR_BUILD_WORKER_IMAGE} == 'Visual Studio 2013' ) { cp C:/pthread-src/bin/x64_MSVC2013.$Env{CONFIGURATION}/pthread_lib.lib C:/pthread-win32/lib }"
  - ps: "if ( $Env{APPVEYOR_BUILD_WORKER_IMAGE} == 'Visual Studio 2015' ) { cp C:/pthread-src/bin/x64_MSVC2015.$Env{CONFIGURATION}/pthread_lib.lib C:/pthread-win32/lib }"
  # build SRT
  - cmake . -DWITH_OPENSSL_INCLUDEDIR=C:/OpenSSL-Win64/include -DWITH_OPENSSL_LIBDIR=C:/OpenSSL-win64/lib/VC/static -DWITH_OPENSSL_LIBRARIES='libeay32MT.lib ssleay32MT.lib' -DWITH_PTHREAD_INCLUDEDIR=C:/pthread-win32/include -DWITH_PTHREAD_LDFLAGS=C:/pthread-win32/lib/pthread_lib.lib
  - msbuild Project.sln
